defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8.9.0

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - ../app
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Test
          command: npm t
      - run:
          name: Code lint
          command: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published

workflows:
  version: 2
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - publish:
          requires:
            - test

experimental:
  notify:
    branches:
      only:
        - master
