defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: build-cache-{{ .Revision }}
          paths:
            - ../app
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Test
          command: npm t
      - run:
          name: Code lint
          command: npm run lint
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Set NPM user
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx published
  docs:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: build-cache-{{ .Revision }}
      - run:
          name: Get the docs template
          command: curl https://raw.githubusercontent.com/omrilotan/mono/master/packages/markt/templates/plain.html > ./template.html
      - run:
          name: Create a webpage from the readme
          command: npx markt --source README.md --destination ./gh-pages/index.html --template ./template.html --title dont-look-up
      - run:
          name: Set git user
          command: curl ci-cd.net/v1/git/user | sh -s a1vy a01101100vy@gmail.com
      - run:
          name: Push gh-pages
          command: curl ci-cd.net/v1/gh/pages | sh -s gh-pages/.

workflows:
  version: 2
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - publish:
          requires:
            - test
      - docs:
          requires:
            - publish
          filters:
            branches:
              only:
                - master

experimental:
  notify:
    branches:
      only:
        - master
